[package]
name = "dragon-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.29.1"
egui = "0.19.0"
gl = "0.14.0"

[build-dependencies]
gl_generator = "0.14.0"
